version: '3'
services:
    db:
        container_name: mysql8
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: sorabh
            MYSQL_DATABASE: lamp_docker
            MYSQL_USER: php8_docker
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
    www: 
        container_name: apache-php8
        build: .
        volumes: 
            - "D:\\www:/var/www/html"
        ports:
            - "80:80"
            - "443:443"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - 8001:80
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306

